name: Matrix Array
on:
  workflow_dispatch:
    inputs:
      apps:
        type: string
        required: true
      configs:
        type: string
        required: true

jobs:
  Example-Matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        apps: ${{ fromJSON(github.event.inputs.app) }}
        configs: ${{ fromJSON(github.event.inputs.config) }}
  
    steps:
      - shell: bash
        with:
          app: ${{ matrix.apps }}
          config: ${{ matrix.configs }}
      - run: echo "starting the ${{ matrix.app }} with ${{ matrix.config }}"
