name: Run App

inputs:
  app:
    type: string
    required: true
  config:
    type: string
    required: true
  apps:
    type: string
    required: true

strategy:
  matrix: "matrix={\"include\": [ {\"app\": \"app 1\"}, {\"app\": \"app 2\"}, {\"app\": \"app 3\"} ] }"

runs:
  using: composite
  steps:
    - name: Configure App
      shell: bash
      with:
        app: ${{ matrix.app }}
      run: echo "starting the ${{ app }} with ${{ inputs.config }}"
