name: Run App

inputs:
  app:
    type: string
    required: true
  config:
    type: string
    required: true
  apps:
    type: string
    required: true

strategy:
  matrix: ${{ fromJson(inputs.apps) }}

runs:
  using: composite
  steps:
    - name: Configure App
      shell: bash
      with:
        app: ${{ matrix.app }}
      run: echo "starting the ${{ app }} with ${{ inputs.config }}"
