name: Run App

inputs:
  app:
    type: string
    required: true
  config:
    type: string
    required: true
  apps:
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Configure App
      shell: bash
      run: |
        IFS="," read -a apps_array <<< $apps
        echo "App 1: ${apps_array[0]}"
        echo "Number of elements in the array: ${#apps_array[@]}"