name: Run App

inputs:
  app:
    type: string
    required: true
  config:
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Configure App
      shell: bash
      run: echo "starting the ${{ inputs.app }} with ${{ inputs.config }}"
