name: Run App
on:
  workflow_call:
    inputs:
      app:
        type: string
        required: true
      config:
        type: string
        required: true

jobs:
  Example App:
    runs-on: ubuntu-latest

    step:
      - shell: bash
      - run: echo "starting the ${{ inputs.app }} with ${{ inputs.config }}"
